all: exercise2.c exercise3.c shellsort/shellsort.c my_sqrt.c
	gcc -o exercise2 exercise2.c shellsort/shellsort.c
	gcc -o exercise3 exercise3.c 

exercise2: exercise2.c
	gcc -o exercise2 exercise2.c shellsort/shellsort.c

exercise3: exercise3.c
	gcc -o exercise3 exercise3.c 

clean:
	rm -rf exercise2 exercise3 shellsort.o